### ISSUE TITLE
 Can't parse 'center'. Sequence item with index 0 has a wrong type

### ISSUE THREAD

**Issue by ShitBro369** [habom2310/Heart-rate-measurement-using-camera#28]
[INFO] Start webcam
D:\anaconda\lib\site-packages\numpy\core\fromnumeric.py:2920: RuntimeWarning: Mean of empty slice.
  out=out, **kwargs)
D:\anaconda\lib\site-packages\numpy\core\_methods.py:85: RuntimeWarning: invalid value encountered in double_scalars
  ret = ret.dtype.type(ret / rcount)
C:\Users\Lenovo\PycharmProjects\Heart-rate-measurement-using-camera\process.py:82: RuntimeWarning: invalid value encountered in true_divide
  norm = interpolated/np.linalg.norm(interpolated)
D:\anaconda\lib\site-packages\pyqtgraph\graphicsItems\PlotCurveItem.py:131: RuntimeWarning: All-NaN slice encountered
  b = (np.nanmin(d), np.nanmax(d))
Traceback (most recent call last):
  File "C:/Users/Lenovo/PycharmProjects/Heart-rate-measurement-using-camera/GUI.py", line 273, in run
    self.main_loop()
  File "C:/Users/Lenovo/PycharmProjects/Heart-rate-measurement-using-camera/GUI.py", line 222, in main_loop
    self.process.run()
  File "C:\Users\Lenovo\PycharmProjects\Heart-rate-measurement-using-camera\process.py", line 39, in run
    frame, face_frame, ROI1, ROI2, status, mask = self.fd.face_detect(self.frame_in)
  File "C:\Users\Lenovo\PycharmProjects\Heart-rate-measurement-using-camera\face_detection.py", line 63, in face_detect
    face_frame = self.fa.align(frame,gray,rects[0]) # align face
  File "D:\anaconda\lib\site-packages\imutils\face_utils\facealigner.py", line 68, in align
    M = cv2.getRotationMatrix2D(eyesCenter, angle, scale)
TypeError: Can't parse 'center'. Sequence item with index 0 has a wrong type
[INFO] Stop webcam
[ WARN:0@19.865] global D:\a\opencv-python\opencv-python\opencv\modules\videoio\src\cap_msmf.cpp (539) `anonymous-namespace'::SourceReaderCB::~SourceReaderCB terminating async callback

**Comment by Magicyp** [comment]
Hello, has this problem been solved？

**Comment by habom2310** [comment]
I've just got it fixed with the newest update. Please pull and try again
